package com.sksamuel.avro4s.internal

import com.sksamuel.avro4s.{DefaultNamingStrategy, NamingStrategy}
import org.apache.avro.Schema

object AvroSchema {

  /**
    * Creates an Avro [[Schema]] for an arbitrary type T.
    *
    * Requires an instance of [[DataTypeFor]] which is usually
    * generated by the avro4s macros.
    *
    * Usage:
    *
    * val schema = SchemaFor[MyType]
    *
    * An implicit [[NamingStrategy]] can be provided to override
    * how the field names are generated.
    */
  def apply[T](implicit dataTypeFor: DataTypeFor[T],
               namingStrategy: NamingStrategy = DefaultNamingStrategy): Schema =
    dataTypeFor.dataType.toSchema(namingStrategy)
}