name: pr_scala_3

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - '*.md'
    branches:
      - master

jobs:
  scala_3_0:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt
          jvm: temurin:11

      - name: run tests
        run: sbt test
