name: pr_scala_2

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - '*.md'
    branches:
      - scala2/*

jobs:
  scala-2_12:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up SBT
        uses: coursier/setup-action@v1
        with:
          apps: sbt
          jvm: temurin:11

      - name: run tests
        run: sbt ++2.12.10 test

  scala-2_13:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up SBT
        uses: coursier/setup-action@v1
        with:
          apps: sbt
          jvm: temurin:11

      - name: run tests
        run: sbt ++2.13.3 test