name: pr_scala_3

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - '*.md'
    branches:
      - master

jobs:
  scala_3_0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt
          jvm: temurin:11

      - name: Run tests
        run: sbt test

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PGP_PASSPHRASE }}

      - name: Publish local
        run: sbt publishLocalSigned
