name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release version"
        default: '5.0.'
        required: true
      branch:
        description: "The branch to release from"
        required: true
        default: 'master'

jobs:
  scala-3:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up SBT
        uses: coursier/setup-action@v1
        with:
          apps: sbt
          jvm: temurin:11

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PGP_PASSPHRASE }}

      - name: GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import_gpg.outputs.name }}"
          echo "email:       ${{ steps.import_gpg.outputs.email }}"

      - name: publish release
        run: sbt publishSigned
        env:
          RELEASE_VERSION: ${{ github.event.inputs.version }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}